version: '3.8'

services:
    app:
        build: .
        volumes:
            - ./:/app
        ports:
            - '3000:3000'
        command: yarn dev
        environment:
            - CHOKIDAR_USEPOLLING=true
        tty: true
