version: '3.8'

services:
    app:
        build: .
        volumes:
            - ./:/app
        ports:
            - '3000:3000'
        command: yarn dev
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        environment:
            - CHOKIDAR_USEPOLLING=true
        tty: true
