version: '3.8'

services:
    app:
        build: .
        volumes:
            - ./:/app
        ports:
            - '3000:3000'
        command: yarn dev
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        environment:
            - CHOKIDAR_USEPOLLING=true
        tty: true

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        volumes:
            - .cache/postgres:/var/lib/postgresql/data
        restart: always
        healthcheck:
            test: pg_isready -U postgres
            interval: 3s
            timeout: 3s
            retries: 5

    redis:
        image: redis:latest
        ports:
            - '6379:6379'
        volumes:
            - .cache/redis:/data
        restart: always
        healthcheck:
            test: redis-cli ping
            interval: 3s
            timeout: 3s
            retries: 5
