version: '3.8'

services:
    app:
        build: .
        volumes:
            - ./:/app
        ports:
            - '3000:3000'
        command: yarn dev
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        environment:
            - CHOKIDAR_USEPOLLING=true
        tty: true

    postgres:
        image: postgres:latest
        volumes:
            - .cache/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        healthcheck:
            test: pg_isready -U postgres
            interval: 5s
            timeout: 5s
            retries: 5

    redis:
        image: redis:latest
        volumes:
            - .cache/redis:/data
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 5s
            retries: 5
